chore: initial draft for stream configs with hints
speedment/jpa-streamer pull request #324
Opened 2023-04-27 09:39 UTC by nitroin

This is a initial draft with some ideas to implements query hints, addressing related #320 issue.

I need to understand how to correctly test this code but I will wait for feedback before proceed further.

2023-05-19 09:37 UTC, julgus commented on streamconfiguration/src/main/java/com/speedment/jpastreamer/streamconfiguration/StreamConfiguration.java
> +    Map<String, Object> hints();
Please add JavaDoc

2023-05-19 09:38 UTC, julgus commented on streamconfiguration/src/main/java/com/speedment/jpastreamer/streamconfiguration/StreamConfiguration.java
> +    StreamConfiguration<T> withHint(final String hintName, final Object value);
Please add JavaDoc

2023-05-19 09:45 UTC, julgus requested changes
Sorry for the delayed response. I think this looks great! Please just write JavaDocs for the added `StreamConfiguration` methods and I'll merge this in. 

These things are always tricky to test. For now, we rely heavily on the jpastreamer-demo repo for manual integration tests before release.

2023-05-19 13:29 UTC, nitroin commented
Added initial javadoc, LGTY?

2023-05-19 13:34 UTC, nitroin commented
I'll open a separate PR for `jpastreamer-demo` to cross validate this change.

2023-05-19 13:54 UTC, julgus commented
> I'll open a separate PR for `jpastreamer-demo` to cross validate this change.

Sounds great!

2023-05-19 13:55 UTC, julgus commented
> Added initial javadoc, LGTY?

Looking good! Did you see my note about signing the Contributor Licence Agreement? See instructions here: [https://github.com/speedment/jpa-streamer/blob/master/CONTRIBUTING.md](https://github.com/speedment/jpa-streamer/blob/master/CONTRIBUTING.md). The signed agreement should be added along with your PR. 

Thanks again!

2023-05-19 14:46 UTC, nitroin commented
This should be ready to go!

_It's works on my machine!_

2023-05-19 14:54 UTC, julgus commented on cla/nitroin
> +Please sign: Manuel Serra_______________ Date: 19/05/2022______
Please update to 2023

2023-05-23 08:17 UTC, julgus approved these changes

2023-05-23 08:17 UTC, merged